### ISSUE TITLE
[QUESTION] Troubles with WebSim example code

### ISSUE THREAD

**Issue by enavarromo** [JdeRobot/WebSim#47]
Hi! I want to ask a few things, cause I'm being unable to launch the easiest code possible in WebSim.

First off all I followed the instructions at "Requirements" section of WebSim Simulator repo. I had some problems installing nodejs, so I ended up with nodejs version 4.2.6 and also node version 11.0.0. Then I tried to launch de web app and execute first example code through the button "RUN":

var myRobot = new RobotI('a-pibot');
myRobot.move(0.5, 0.5);

but the robot does nothing. I tried it launching server.js with both, node and nodejs and refreshing the page, but there's no difference at all:
![duda_websim](https://user-images.githubusercontent.com/16896156/47963507-8982c900-e02d-11e8-88af-efb95985d94b.png)

I'm pretty sure I'm doing something wrong, but I really don't know what.
Any help would be appreciated, thank you!
Eloy.

**Comment by enavarromo** [comment]
That's right! I tried 2 repos:
the one you refer to:
https://github.com/RoboticsURJC-students/2018-tfg-alvaro_paniagua.git

and also:
https://github.com/JdeRobot/WebSim.git
But this one fails in all kind of different ways. With nodejs it just crushes at launch, and with node, it starts properly, and then when I try to execute the example from the web, the robot does nothing, and the server execution throws an error:
![errores_websim_main](https://user-images.githubusercontent.com/16896156/47964149-b804a200-e035-11e8-9b6e-561d73e97a79.png)

I will then wait for the update of your repo "https://github.com/RoboticsURJC-students/2018-tfg-alvaro_paniagua" and try again, thank you!

**Comment by AlvaroPaniaguaT** [comment]
Fixed problems, now you can run it on local PC or you can access through Github Pages on following link: https://jderobot.github.io/WebSim/
